modified:   bawkpack

diff --git a/bawkpack b/bawkpack
--- a/bawkpack
+++ b/bawkpack
@@ -1,10 +1,11 @@
 #!/bin/sh
 
-#    __               __                  __
-#   / /  ___ __    __/ /__ ___  ___ _____/ /__
-#  / _ \/ _ `/ |/|/ /  '_// _ \/ _ `/ __/  '_/
-# /_.__/\_,_/|__,__/_/\_\/ .__/\_,_/\__/_/\_\
-#                       /_/
+#     ____
+#    / __ )            __                  __
+#   / __  /__ __    __/ /__ ___  ___ _____/ /__
+#  / /_/ / _ `/ |/|/ /  '_// _ \/ _ `/ __/  '_/
+# /_____/\_,_/|__,__/_/\_\/ .__/\_,_/\__/_/\_\
+#                        /_/
 
 # File:         bawkpack
 # Description:  Packages list installer that SuperB
@@ -28,29 +29,89 @@
 
 
 # Values
+pwd="$PWD"
+
 list=${1:-$BAWKPACK_LIST}
-mainpm=${2:-$BAWKPACK_MAINPM}
 [ ! -f "$list"   ] && echo 'Packages list is not found, please `export BAWKPACK_LIST=path/to/packages`' && exit 1
-[ ! -n "$mainpm" ] && echo 'main packages manager is unset, please `export BAWKPACK_MAINPM=[Pacman|APT|XBPS]`' && exit 1
+
+bawkpack_local="${XDG_CACHE_HOME:-"$HOME/.local/share"}/bawkpack"
 bawkpack_cache="${XDG_CACHE_HOME:-"$HOME/.cache"}/bawkpack_cache"
 awk '{gsub("#.*$", "");print}' "$list" > "$bawkpack_cache"
+
                              pms="$mainpm"
 [ "$mainpm"  = 'Pacman' ] && pms="$pms AUR"
                              pms="$pms Flatpak"
 [ "$mainpm" != 'XBPS'   ] && pms="$pms Snap"
+
+if   [ -f '/bin/pacman'       ]; then mainpm='Pacman'
+elif [ -f '/bin/apt'          ]; then mainpm='APT'
+elif [ -f '/bin/xbps-install' ]; then mainpm='XBPS'
+fi
+
+
+# Functions
+setup_pacman() {
+	sudo pacman --sync --refresh --sysupgrade --noconfirm --needed
+}
+
+setup_apt() {
+	sudo apt update --assume-yes
+	sudo apt upgrade --assume-yes
+}
+
+setup_xbps() {
+	sudo xbps-install --sync --update --yes
+	sudo xbps-install --sync --update --yes void-repo-nonfree void-repo-multilib void-repo-multilib-nonfree void-repo-debug
+}
+
+setup_aur() {
+	sudo pacman --sync --refresh --noconfirm --needed git base-devel
+
+	git clone https://aur.archlinux.org/yay.git "$bawkpack_local/yay"
+	cd "$bawkpack_local/yay"
+	makepkg -si
+	cd $pwd
+}
+
+setup_flatpak() {
+	if   [ $mainpm = 'Pacman' ]; then sudo pacman --sync --refresh --noconfirm --needed flatpak
+	elif [ $mainpm = 'APT'    ]; then sudo apt install --assume-yes flatpak gnome-software-plugin-flatpak
+	elif [ $mainpm = 'XBPS'   ]; then sudo xbps-install --sync --yes flatpak
+	fi
+
+	flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
+}
+
+setup_snap() {
+	if   [ $mainpm = 'Pacman' ]; then
+		sudo pacman --sync --refresh --noconfirm --needed git
+
+		git clone https://aur.archlinux.org/snapd.git "$bawkpack_local/snap"
+		cd "$bawkpack_local/snap"
+		makepkg -si
+		cd $pwd
+
+		sudo systemctl enable --now snapd.socket
+		sudo ln -s /var/lib/snapd/snap /snap
+	elif [ $mainpm = 'APT' ]; then
+		sudo apt install --assume-yes snapd
+	fi
+
+	snap install core
+}
 
 
 # Start
 for pm in $pms; do
 	if [ -n "$(awk '{print}' "$bawkpack_cache")" ]; then
 		case $pm in
-			'Pacman')    pm_launcher='sudo pacman --sync --refresh --noconfirm --needed' ; pm_mark='PAC' ;;
-			'APT')       pm_launcher='sudo apt install --assume-yes'                     ; pm_mark='APT' ;; #TODO
-			'XBPS')      pm_launcher='sudo xbps-install --sync --yes'                    ; pm_mark='XBP' ;;
-			'AUR')       pm_launcher='yay -Sy --nodiffmenu --save'                       ; pm_mark='AUR' ;; #FIXME
-			'Flatpak')   pm_launcher='sudo flatpak install'                              ; pm_mark='FLA' ;; #FIXME
-			'Snap')      pm_launcher='sudo snap install'                                 ; pm_mark='SNA' ;; #FIXME
-			*)           echo "'$pm' packages manager not found"                         ; exit 1        ;;
+			'Pacman')    pm_launcher='sudo pacman --sync --refresh --noconfirm --needed'; pm_mark='PAC'; setup_pacman  ;;
+			'APT')       pm_launcher='sudo apt install --assume-yes'                    ; pm_mark='APT'; setup_apt     ;;
+			'XBPS')      pm_launcher='sudo xbps-install --sync --yes'                   ; pm_mark='XBP'; setup_xbps    ;;
+			'AUR')       pm_launcher='yay -Sy --nodiffmenu --save'                      ; pm_mark='AUR'; setup_aur     ;;
+			'Flatpak')   pm_launcher='sudo flatpak install'                             ; pm_mark='FLA'; setup_flatpak ;;
+			'Snap')      pm_launcher='sudo snap install'                                ; pm_mark='SNA'; setup_snap    ;;
+			*)           echo "'$pm' packages manager not found"                                       ; exit 1        ;;
 		esac
 
 		echo "Installing $pm Packages:"
@@ -61,4 +122,7 @@ for pm in $pms; do
 done
 
 
-exit 0
+exit 0 #  ________                     __
+       # /_  __/ /  ___   ___ ___  ___/ /
+       #  / / / _ \/ -_) / -_) _ \/ _  /
+       # /_/ /_//_/\__/  \__/_//_/\_,_/
